openai:
  api_key: YOUR_API_KEY
  api_base: dummy
  api_version: 2023-05-15
  deployment_name: gpt-35-turbo
  context_length: context-4k
  pricing:
    gpt-35-turbo:
        context-4k:
          input-1k: 0.0015
          output-1k: 0.002

